### Site Settings ### #run bundle exec jekyll serve
title               : Hai Anh Le
description         : Passionate data scientist 🤓 with extensive experience in quantitative research 🧬 📈. Proficient in visualising complex data 🎨 and producing comprehensive reports.
baseurl             : "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html

### Author Info ###
author:
  name              : Hai
  image             : https://avatars.githubusercontent.com/u/60798941?v=4
  email             : l.haimcl@gmail.com
  github            : lehai-ml
  linkedin          : haileanh
  soundcloud        : hai_lofi
  
### Collections ###
collections:
  projects:
    output: true

## Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
