### Site Settings ###
title               : Hai Anh Le
description         : Passionate health data analyst 🤓 with extensive experience in research 🧬 and quantitative analysis 📈. Proficient in visualising complex data 🎨 and producing comprehensive reports. Excited for new opportunities to implement data-related solutions.
baseurl             : "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html

### Author Info ###
author:
  name              : Hai
  image             : https://media.licdn.com/dms/image/C4D03AQFnNqGVVpBt2A/profile-displayphoto-shrink_400_400/0/1638654589137?e=1677110400&v=beta&t=HhmK63kwVVCBdk0vGxjgpxBcPL6sMLsekyW-fz5-v7g
  email             : le.hai@kcl.ac.uk
  github            : lehai-ml
  linkedin          : haileanh
  soundcloud        : hai_lofi

### Collections ###
collections:
  projects:
    output: true

## Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
